### ISSUE TITLE
Question on Normalization

### ISSUE THREAD

**Issue by chschroeder** [mourga/contrastive-active-learning#4]
Hi,

a while ago I re-implemented your Contrastive Active Learning (CAL) strategy following your paper. The paper is very well written therefore it was easy to understand, but I am uncertain about a minor detail:

When using CAL and BERT Embeddings, do you apply L2 normalization here as well?
You described this in the paper for BERT-K-Means but there is no statement on this regarding CAL.

**Comment by mourga** [comment]
Hey @chschroeder, thanks for your comment! You are right, in my experiments I did apply normalization; I thought I had mentioned that to the paper as well. Like you said this is a small detail and I do not believe the distance between the embeddings will change without normalization. I just followed previous work on this and kept it. :)

**Comment by chschroeder** [comment]
No worries, I might have missed something as well. In any case, this has clarified my question :). Thank you very much for quick reply!

**Comment by mourga** [comment]
No worries, thank you @chschroeder for reaching out!! :)
